### ISSUE TITLE
Seeking for help - BAG file - qrc_options.yaml

### ISSUE THREAD

**Issue by danielrayray43041** [ucb-art/cds_ff_mpt#2]
Hi there,

I would like to ask is there a lost file, qrc_options.yaml ,in this package. 
Since I went to bag_config.yaml to see the 'RCX runset' while extracting RC, there needs to be a 'qrc_options.yaml' file, but I can't find it anywhere under pvs_step file, even I tried to use ctrl F to search the whole file downloaded from here.
Therefore, if you have some methods, please let me know.

Much appreciated
![qrc_options yaml](https://user-images.githubusercontent.com/64354911/81051403-33c60000-8ef4-11ea-8174-01cae51fd33f.png)

Daniel

**Comment by ayan-biswas** [comment]
fixed - please use latest updates
